import {
    Box,
    Divider,
    Stack,
    StackDivider,
    Text,
    useColorModeValue as mode,
  } from '@chakra-ui/react'
  import * as React from 'react'
  import { FaMobileAlt, FaShieldAlt } from 'react-icons/fa'
  import { Description } from './Description'
  import { HeadingGroup } from '../AccountPage/HeadingGroup'
  
  const VerificationComponent = () => {
    return (

          <div>
              <HeadingGroup
              title="Verification options"
              description="Add an extra layer of security and protect your account."
              />
              <Box
                rounded={{
                  lg: 'lg',
                }}
                bg={mode('white', 'gray.700')}
                maxW="3xl"
                mx="auto"
                my='6'
                shadow="base"
                overflow="hidden"
              >
                <Box px="6" py="1">
                </Box>
                <Stack spacing="6" divider={<StackDivider />} py="5" px="8">
                  <Description isRecommended title="Authenticator" icon={<FaShieldAlt />}>
                    Enter a code generated by your authenticator app to confirm it’s you.
                  </Description>
                  <Description title="Phone verification" icon={<FaMobileAlt />}>
                    Receive a text to your mobile phone to confirm it’s you on login.
                  </Description>
                </Stack>
              </Box>
          </div>
    )
  }

export default VerificationComponent;